# nixpacks.toml
[phases.setup]
nixPkgs = [
  "glib",
  "gobject-introspection",
  "gtk3",
  "libx11",
  "libxcomposite",
  "libxdamage",
  "libxrandr",
  "nss",
  "atk",
  "cups",
  "dbus",
  "libxfixes",
  "libxrender",
  "libxtst",
  "alsa-lib",
  "mesa",
  "pango",
  "gdk-pixbuf",
  "libdrm",
  "expat"
]
