[phases.setup]
nixPkgs = [
  "nodejs",
  "glib",
  "gobject-introspection",
  "gtk3",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXrandr",
  "xorg.libXfixes",
  "xorg.libXrender",
  "xorg.libXtst",
  "atk",
  "cups",
  "dbus",
  "alsa-lib",
  "mesa",
  "pango",
  "gdk-pixbuf",
  "libdrm",
  "expat",
  "nss",
  "freetype",
  "fontconfig",
  "xorg.libxcb",
  "xorg.libxshmfence",
  "xorg.libXext",
  "xorg.libXi"
]
