[phases.setup]
nixPkgs = [
  "nodejs",
  # Core GLib and GObject libraries
  "glib",
  "gobject-introspection",
  "glibc",
  # GTK and UI libraries
  "gtk3",
  "atk",
  "pango",
  "gdk-pixbuf",
  "cairo",
  # X11 libraries
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXrandr",
  "xorg.libXfixes",
  "xorg.libXrender",
  "xorg.libXtst",
  "xorg.libXext",
  "xorg.libXi",
  "xorg.libxcb",
  "xorg.libxshmfence",
  "xorg.libXScrnSaver",
  # Audio and graphics
  "alsa-lib",
  "mesa",
  "libdrm",
  "cups",
  # System libraries
  "dbus",
  "expat",
  "nss",
  "nspr",
  "freetype",
  "fontconfig",
  # Additional libraries often needed for Chrome
  "libxkbcommon",
  "at-spi2-atk",
  "at-spi2-core",
  "libuuid",
  "libappindicator-gtk3",
  # Chromium-specific dependencies
  "chromium"
]