[phases.setup]
nixPkgs = [
  "glib",
  "gobject-introspection",
  "gtk3",
  "libX11",
  "libXcomposite",
  "libxdamage",
  "libXrandr",
  "nss",
  "atk",
  "cups",
  "dbus",
  "libXfixes",
  "libXrender",
  "libXtst",
  "alsa-lib",
  "mesa",
  "pango",
  "gdk-pixbuf",
  "libdrm",
  "expat"
]
